### ISSUE TITLE
Create endpoint for vendors

### ISSUE THREAD

**Issue by 5h15h1r** [5h15h1r/organization-app#3]
### Description 
The task is to create endpoints for vendors.
Create a schema for vendors with following fields:

- Name - varchar, Not Null, unique
- Phone - varchar
- Email - varchar
- organization_id - uuid, references: organizations

### Subtasks

- [x] Create migration to set up table column corresponding with the fields above.
- [x] Create routes for vendors.
- [x] Create CRUD (Create, Read, Update, Delete) endpoints for vendors API.
- [x] Write tests for vendors context and the associated controller.
