### ISSUE TITLE
implement audit log

### ISSUE THREAD

**Issue by 5h15h1r** [5h15h1r/organization-app#7]
### Description
This task is to implement audit log in out application. The audit log store all the create, update, delete operations done on the existing tables.
Create a schema for the audit log table with following fields:
- id (UUID)
- organization_id (UUID)
- user_id (UUID)
- action(CREATE, UPDATE, DELETE)
- table_name (varchar)
- record_id (UUID)
- old_data (jsonb)
- new_data (jsonb)
- ip_address (varchar)
- user_agent (varchar)
### Subtasks
- [x] Create migrations for audit log table with the fields mentioned above.
- [x] Create routes for audit log endpoint
- [x] Create context for audit log
- [x] Make existing controller to add changes to audit log when doing CREATE, UPDATE, DELETE operation.
- [x] Write tests for the audit log.
