### ISSUE TITLE
Implement Oban

### ISSUE THREAD

**Issue by 5h15h1r** [5h15h1r/organization-app#9]
### Overview
This task is to implement asynchronous audit log insertion
### Subtasks
- [x] Create migration for oban.
- [x] Set up oban configuration.
- [x] Implement oban for async audit log insertion.
